### ISSUE TITLE
Not working on nodejs v19 termux

### ISSUE THREAD

**Issue by bajrangCoder** [renhiyama/smux#1]
I love this project idea but your termux script is not working and gives below error:

```
~ $ smux-server
/data/data/com.termux/files/home/.smux/server/node_modules/@honojs/node-server/dist/globals.js:23
    global.crypto = node_crypto_1.default;
                  ^

TypeError: Cannot set property crypto of #<Object> which has only a getter
    at installGlobals (/data/data/com.termux/files/home/.smux/server/node_modules/@honojs/node-server/dist/globals.js:23:19)
    at Object.<anonymous> (/data/data/com.termux/files/home/.smux/server/node_modules/@honojs/node-server/dist/server.js:8:30)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/.smux/server/node_modules/@honojs/node-server/dist/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)

Node.js v19.4.0
~ $
```

And also provide more about your project in readme so contributers will come

And i also code on mobile with Acode+termux

**Comment by renhiyama** [comment]
`smux-server` on termux runs fine. Did you consider running on nodejs v18?

**Comment by renhiyama** [comment]
Also what do you mean by provide something more in readme so more contributors will come? It's in wip and if u want to help, try joining our discord server to discuss, thanks.

**Comment by bajrangCoder** [comment]
Yep , i had joined the discord but there is nothing related with smux
Ok i will try it on v18
And the server is help in performing filesystem operation on device?
And what you think if the server will be written in rust?

**Comment by renhiyama** [comment]
There's a channel #smux on discord server. You need to get verified before though in order to access it.

**Comment by renhiyama** [comment]
No the server doesn't help in improving performance, it simply exists as a easy way to call certain filesystem APIs over http. While I agree rust is cool, it will waste a lot of my time on building and compiling server rather than working on it. I can easily code during that time. Nodejs based server will be definitely fine as your usecase will be only one person based and I don't wanna over engineer it.

**Comment by bajrangCoder** [comment]
Ok , then you have to do something so the server can run with any version..

By the way, i will try improve server
Thank for quick response

**Comment by renhiyama** [comment]
Try not to change server package from `hono` to something else. Hono doesn't have any dependency which uses less storage on ur phone and installs faster than other server frameworks like expressjs or fastify.

**Comment by bajrangCoder** [comment]
I will not use any `nodejs framework`, i will use either `FastAPI(Python)` or `Rocket(Rust)`. Because they are much **faster** than any other. And also it will good to add a **token generation** in the client side so while connecting it became safe.
Can we talk about it on discord server?

**Comment by renhiyama** [comment]
Not python because I am still learning it in school, and it has a bigger installation size on termux comparing it with nodejs. Not rust because I don't want to compile binaries for every arch and stuff like that, not to mention I completely forgot how to write it and compile times will heat my phone during dev

**Comment by renhiyama** [comment]
> I will not use any `nodejs framework`, i will use either `FastAPI(Python)` or `Rocket(Rust)`. Because they are much **faster** than any other. And also it will good to add a **token generation** in the client side so while connecting it became safe.
> Can we talk about it on discord server?

Sure in #smux
